### ISSUE TITLE
Unhandled exception after disabling VPN

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#132]
After unsuccesful version update ( I still had green progress bar, but I have no idea why, update most likely stopped) i disabled VPN, and got error
![obraz](https://user-images.githubusercontent.com/93384978/147732003-516dd5d2-c9be-4cf2-9ee2-37c124aa078a.png)

************** Tekst wyjątku **************
System.Data.Odbc.OdbcException (0x80131937): ERROR [08S01] Communication link failure
   at System.Data.Odbc.OdbcDataReader.Read()
   at JustData.Netezza.<BuilSchemaSqlLiteAsyncForNz>g__makeOneDb|10_4(String connectionName, String baza) in D:\C_CPY\source\repos\NZ-SQL-IDE\JustData\Netezza.cs:line 587
   at JustData.Netezza.<>c__DisplayClass10_0.<BuilSchemaSqlLiteAsyncForNz>b__7(String baza) in D:\C_CPY\source\repos\NZ-SQL-IDE\JustData\Netezza.cs:line 328
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.CountAggregationOperator`1.CountAggregationOperatorEnumerator`1.MoveNextCore(Int32& currentElement)
   at System.Linq.Parallel.InlinedAggregationOperatorEnumerator`1.MoveNext(TIntermediate& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by andrzejchmiel3** [comment]
(tested on v29 ) Same problem with easier to recreate conditions:
1. Full schema refresh
2. During that, pull internet plug.

**Comment by KrzysztofDusko** [comment]
timeout of downloading file extended from 10 seconds to 15 minutes

**Comment by KrzysztofDusko** [comment]
thanks for pointing this out.
Please check with >=20211231

**Comment by andrzejchmiel3** [comment]
Unhandled exception seems fixed. But after it stopped refreshing because of handled problem, the status (text in lower right corner) still says "[database] - schema refreshing"
Also about that status, I noticed that when you stop refreshing by closing program, then open it again, it's refreshing database but status is "ready" instead of "refreshing.."

**Comment by KrzysztofDusko** [comment]
thank you for accuracy. plase check with 20220103

**Comment by andrzejchmiel3** [comment]
Now it's both working and accordingly described in status, thank you, closing thread
