### ISSUE TITLE
Długi kod - bład w hisotrii

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/Just-Data#136]
```
Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FastColoredTextBoxNS.FastColoredTextBox.DrawMarkers(PaintEventArgs e, Pen servicePen) in D:\C_CPY\source\repos\ProgramingTextBox\source\FastColoredTextBox.cs:line 5390
   at FastColoredTextBoxNS.FastColoredTextBox.OnPaint(PaintEventArgs e) in D:\C_CPY\source\repos\ProgramingTextBox\source\FastColoredTextBox.cs:line 5324
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at FastColoredTextBoxNS.FastColoredTextBox.WndProc(Message& m) in D:\C_CPY\source\repos\ProgramingTextBox\source\FastColoredTextBox.cs:line 2969
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```
![image](https://user-images.githubusercontent.com/69449360/148200255-6b6998a8-aa44-4369-8096-45e8ac0df33f.png)

**Comment by KrzysztofDusko** [comment]
[kod_blad.txt](https://github.com/KrzysztofDusko/Just-Data/files/7814061/kod_blad.txt)
