### ISSUE TITLE
Unhandled exception on closing log 

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#164]
If you close log **while query is running**, and that query would result in error, you get unhandled exception

Example: select 1/0
By log i mean like below:
![obraz](https://user-images.githubusercontent.com/93384978/151797823-e13181ef-763c-403d-9029-dfcf9fc5c369.png)

Closing it while query is running results in :
![obraz](https://user-images.githubusercontent.com/93384978/151797569-4a92a2a8-061b-418a-bd76-d4969bab5582.png)

System.NullReferenceException: Object reference not set to an instance of an object.
   at JustData.BaseWindow.<>c__DisplayClass354_11.<RunNzSQL>b__40() in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 6713
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at JustData.BaseWindow.RunNzSQL(Int32 mode, ExportOptions opcjaEksportu, Boolean explain, String filePath) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 6678
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by KrzysztofDusko** [comment]
thank you for reporting this. In your opinion should be possible to close log when sql is running ?

**Comment by andrzejchmiel3** [comment]
I would say - no. Or at least it should ask if we want to abort query before closing. Currently it seems to abort select, as I'm not getting any results, but I don't think it is really aborted. So it may lead to problems like heavy queries left running.

Also, when query is running (for example - insert), closing log would mean I wouldn't get feedback it insert really happened.

**Comment by andrzejchmiel3** [comment]
Ok, in current version I'm not getting that exception, so it seems solved, thank you
