### ISSUE TITLE
Unhandled exception when clicking on pinned results

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#182]
I'm getting exception while clicking on results of pinned down columns.

************** Tekst wyjątku **************
System.InvalidOperationException: Właściwości FirstDisplayedScrollingColumnIndex nie można ustawić jako kolumny zablokowanej.
   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingColumnIndex(Int32 value)
   at JustData.MyDataGridView.dataGridView1_SelectionChanged(Object sender, EventArgs e) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\MyDataGridView.cs:line 3034
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

How to get it:
1. Run sql
select 1 as kol1 , 2 as kol2 
2. Pin down first column. Pin down second column
3. Click on "2" (result of second column)

**Comment by KrzysztofDusko** [comment]
related with https://github.com/KrzysztofDusko/Just-Data/issues/166

**Comment by KrzysztofDusko** [comment]
please check

**Comment by andrzejchmiel3** [comment]
Now seems to be fine, no exception. Thank you
