### ISSUE TITLE
Netezza schema Error

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/Just-Data#199]
![image](https://user-images.githubusercontent.com/69449360/207538468-b07f034c-06ba-468e-8d96-89cadc0a9274.png)

**Comment by KrzysztofDusko** [comment]
```
The given key 'DATABASE_NAME' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at JustData.DynamicCollectionForNetteza.GetEnumerator()+MoveNext() in \source\repos\NZ-SQL-IDE\JustData\Additions.cs:line 472
   at FastColoredTextBoxNS.AutocompleteListView.DoAutocomplete(Boolean forced) in \source\repos\ProgramingTextBox\source\AutocompleteMenu.cs:line 407
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
