### ISSUE TITLE
duplicates in netezza schema

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/Just-Data#2]
```SQL
code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: BAZY_TABELE_OPISY.ID_TABELI
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at JustData.BaseWindow.<>c__DisplayClass381_0.<BuilSchemaSqlLiteAsyncForNz>b__2()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at JustData.BaseWindow.BuilSchemaSqlLiteAsyncForNz(String connectionName)
   at JustData.BaseWindow.cbConnections_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
```

_V_OBJ_RELATION_XDB, _V_OBJECT_DATA

**Comment by KrzysztofDusko** [comment]
```SQL
 SELECT * FROM _V_OBJECT_DATA WHERE SCHEMA = 'DEFINITION_SCHEMA'
```
