### ISSUE TITLE
Nieobsłużony wyjątek przy próbie zrobienia reecreate na nowej tabeli

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#68]
************** Tekst wyjątku **************
System.Runtime.InteropServices.ExternalException (0x800401D0): Żądana operacja schowka nie powiodła się.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at JustData.BaseWindow.recreateTable_Click(Object sender, EventArgs e) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 11807
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Odtworzenie:
1. CREATE TABLE NAZWA_BAZY..TAB_TEST_ASDFASFGAS as select 1
2. Prawym na nazwę tabeli i refresh schemta for selected table
3. Odszukać ręcznie w schemacie tę tabelę, prawym i recreate to clipboard.

**Comment by KrzysztofDusko** [comment]
problem występuje z konfiguracja komputera. Wiąże się bezpośrednio z agresywną strategią zabezpieczeń komputera (jakieś oprogramowanie nie pozwala Just Data użyć schowka) sprawę należy wyjaśnić z jednostką odpowiedzialną za bezpieczeństwo teleinformatyczne.

**Comment by KrzysztofDusko** [comment]
Potwierdzone - temat dla jednostki bezpieczeństwa/administratora komputera.
